use iced::Color;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum PlayerTheme {
    #[default]
    EmeraldDark,
    MidnightCyberpunk,
    NordicFrost,
    AmberSunset,
    Dracula,
    SolarizedLight,
}

#[derive(Debug, Clone, Copy)]
pub struct ThemePalette {
    pub name: &'static str,
    pub description: &'static str,
    pub is_dark: bool,
    pub bg_root: Color,
    pub bg_panel: Color,
    pub bg_card: Color,
    pub bg_card_hover: Color,
    pub border: Color,
    pub border_subtle: Color,
    pub accent: Color,
    pub accent_hover: Color,
    pub accent_text: Color,
    pub text_primary: Color,
    pub text_secondary: Color,
    pub text_muted: Color,
    pub nav_selected_bg: Color,
    pub nav_selected_border: Color,
    pub row_item_bg: Color,
    pub row_hover_bg: Color,
    pub row_selected_bg: Color,
    pub row_playing_bg: Color,
    pub row_playing_border: Color,
    pub badge_bg: Color,
    pub badge_text: Color,
    pub visualizer_low: Color,
    pub visualizer_mid: Color,
    pub visualizer_high: Color,
}

impl PlayerTheme {
    pub fn all() -> &'static [PlayerTheme] {
        &[
            PlayerTheme::EmeraldDark,
            PlayerTheme::MidnightCyberpunk,
            PlayerTheme::NordicFrost,
            PlayerTheme::AmberSunset,
            PlayerTheme::Dracula,
            PlayerTheme::SolarizedLight,
        ]
    }

    pub fn next(&self) -> Self {
        match self {
            Self::EmeraldDark => Self::MidnightCyberpunk,
            Self::MidnightCyberpunk => Self::NordicFrost,
            Self::NordicFrost => Self::AmberSunset,
            Self::AmberSunset => Self::Dracula,
            Self::Dracula => Self::SolarizedLight,
            Self::SolarizedLight => Self::EmeraldDark,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::EmeraldDark => "Emerald Dark",
            Self::MidnightCyberpunk => "Midnight Cyberpunk",
            Self::NordicFrost => "Nordic Frost",
            Self::AmberSunset => "Amber Sunset",
            Self::Dracula => "Dracula",
            Self::SolarizedLight => "Solarized Light",
        }
    }

    pub fn palette(&self) -> ThemePalette {
        match self {
            Self::EmeraldDark => ThemePalette {
                name: "Emerald Dark",
                description: "Deep obsidian slate with energetic emerald green and cyan highlights",
                is_dark: true,
                bg_root: Color::from_rgb8(11, 15, 23),
                bg_panel: Color::from_rgb8(18, 24, 38),
                bg_card: Color::from_rgb8(24, 32, 50),
                bg_card_hover: Color::from_rgb8(32, 42, 65),
                border: Color::from_rgb8(38, 50, 75),
                border_subtle: Color::from_rgb8(28, 38, 58),
                accent: Color::from_rgb8(16, 185, 129),
                accent_hover: Color::from_rgb8(5, 150, 105),
                accent_text: Color::WHITE,
                text_primary: Color::WHITE,
                text_secondary: Color::from_rgb8(148, 163, 184),
                text_muted: Color::from_rgb8(100, 116, 139),
                nav_selected_bg: Color::from_rgb8(6, 78, 59),
                nav_selected_border: Color::from_rgb8(16, 185, 129),
                row_item_bg: Color::from_rgb8(16, 20, 29),
                row_hover_bg: Color::from_rgb8(26, 34, 49),
                row_selected_bg: Color::from_rgb8(30, 48, 80),
                row_playing_bg: Color::from_rgb8(6, 78, 59),
                row_playing_border: Color::from_rgb8(16, 185, 129),
                badge_bg: Color::from_rgb8(30, 41, 59),
                badge_text: Color::from_rgb8(52, 211, 153),
                visualizer_low: Color::from_rgb8(16, 185, 129),
                visualizer_mid: Color::from_rgb8(6, 182, 212),
                visualizer_high: Color::from_rgb8(245, 158, 11),
            },
            Self::MidnightCyberpunk => ThemePalette {
                name: "Midnight Cyberpunk",
                description: "Obsidian void infused with neon purple, electric magenta, and cyan",
                is_dark: true,
                bg_root: Color::from_rgb8(10, 8, 18),
                bg_panel: Color::from_rgb8(18, 14, 32),
                bg_card: Color::from_rgb8(26, 20, 46),
                bg_card_hover: Color::from_rgb8(38, 30, 66),
                border: Color::from_rgb8(65, 42, 110),
                border_subtle: Color::from_rgb8(42, 28, 75),
                accent: Color::from_rgb8(168, 85, 247),
                accent_hover: Color::from_rgb8(147, 51, 234),
                accent_text: Color::WHITE,
                text_primary: Color::WHITE,
                text_secondary: Color::from_rgb8(196, 181, 253),
                text_muted: Color::from_rgb8(139, 124, 180),
                nav_selected_bg: Color::from_rgb8(88, 28, 135),
                nav_selected_border: Color::from_rgb8(168, 85, 247),
                row_item_bg: Color::from_rgb8(18, 13, 30),
                row_hover_bg: Color::from_rgb8(34, 25, 60),
                row_selected_bg: Color::from_rgb8(60, 25, 95),
                row_playing_bg: Color::from_rgb8(88, 28, 135),
                row_playing_border: Color::from_rgb8(236, 72, 153),
                badge_bg: Color::from_rgb8(45, 25, 80),
                badge_text: Color::from_rgb8(236, 72, 153),
                visualizer_low: Color::from_rgb8(168, 85, 247),
                visualizer_mid: Color::from_rgb8(236, 72, 153),
                visualizer_high: Color::from_rgb8(6, 182, 212),
            },
            Self::NordicFrost => ThemePalette {
                name: "Nordic Frost",
                description: "Cool Arctic palette with Nord slate and glacial ice blue accents",
                is_dark: true,
                bg_root: Color::from_rgb8(36, 41, 51),
                bg_panel: Color::from_rgb8(46, 52, 64),
                bg_card: Color::from_rgb8(59, 66, 82),
                bg_card_hover: Color::from_rgb8(67, 76, 94),
                border: Color::from_rgb8(76, 86, 106),
                border_subtle: Color::from_rgb8(60, 68, 84),
                accent: Color::from_rgb8(136, 192, 208),
                accent_hover: Color::from_rgb8(129, 161, 193),
                accent_text: Color::from_rgb8(46, 52, 64),
                text_primary: Color::from_rgb8(236, 239, 244),
                text_secondary: Color::from_rgb8(216, 222, 233),
                text_muted: Color::from_rgb8(142, 156, 178),
                nav_selected_bg: Color::from_rgb8(43, 76, 100),
                nav_selected_border: Color::from_rgb8(136, 192, 208),
                row_item_bg: Color::from_rgb8(40, 46, 58),
                row_hover_bg: Color::from_rgb8(54, 62, 78),
                row_selected_bg: Color::from_rgb8(64, 76, 96),
                row_playing_bg: Color::from_rgb8(43, 76, 100),
                row_playing_border: Color::from_rgb8(136, 192, 208),
                badge_bg: Color::from_rgb8(54, 65, 85),
                badge_text: Color::from_rgb8(143, 188, 187),
                visualizer_low: Color::from_rgb8(136, 192, 208),
                visualizer_mid: Color::from_rgb8(129, 161, 193),
                visualizer_high: Color::from_rgb8(163, 190, 140),
            },
            Self::AmberSunset => ThemePalette {
                name: "Amber Sunset",
                description: "Rich espresso charcoal with glowing gold and warm amber embers",
                is_dark: true,
                bg_root: Color::from_rgb8(20, 16, 14),
                bg_panel: Color::from_rgb8(30, 24, 21),
                bg_card: Color::from_rgb8(40, 32, 28),
                bg_card_hover: Color::from_rgb8(52, 42, 36),
                border: Color::from_rgb8(68, 54, 46),
                border_subtle: Color::from_rgb8(48, 38, 32),
                accent: Color::from_rgb8(245, 158, 11),
                accent_hover: Color::from_rgb8(217, 119, 6),
                accent_text: Color::from_rgb8(24, 18, 12),
                text_primary: Color::from_rgb8(254, 243, 199),
                text_secondary: Color::from_rgb8(217, 189, 162),
                text_muted: Color::from_rgb8(156, 130, 110),
                nav_selected_bg: Color::from_rgb8(85, 45, 12),
                nav_selected_border: Color::from_rgb8(245, 158, 11),
                row_item_bg: Color::from_rgb8(26, 21, 18),
                row_hover_bg: Color::from_rgb8(45, 36, 30),
                row_selected_bg: Color::from_rgb8(65, 45, 30),
                row_playing_bg: Color::from_rgb8(85, 45, 12),
                row_playing_border: Color::from_rgb8(245, 158, 11),
                badge_bg: Color::from_rgb8(50, 35, 25),
                badge_text: Color::from_rgb8(251, 191, 36),
                visualizer_low: Color::from_rgb8(245, 158, 11),
                visualizer_mid: Color::from_rgb8(251, 146, 60),
                visualizer_high: Color::from_rgb8(239, 68, 68),
            },
            Self::Dracula => ThemePalette {
                name: "Dracula",
                description: "Vampiric dark theme with neon pink, purple, and radioactive mint",
                is_dark: true,
                bg_root: Color::from_rgb8(33, 34, 44),
                bg_panel: Color::from_rgb8(40, 42, 54),
                bg_card: Color::from_rgb8(52, 55, 70),
                bg_card_hover: Color::from_rgb8(68, 71, 90),
                border: Color::from_rgb8(85, 88, 110),
                border_subtle: Color::from_rgb8(60, 62, 80),
                accent: Color::from_rgb8(255, 121, 198),
                accent_hover: Color::from_rgb8(240, 100, 180),
                accent_text: Color::WHITE,
                text_primary: Color::from_rgb8(248, 248, 242),
                text_secondary: Color::from_rgb8(189, 147, 249),
                text_muted: Color::from_rgb8(130, 135, 155),
                nav_selected_bg: Color::from_rgb8(70, 40, 75),
                nav_selected_border: Color::from_rgb8(255, 121, 198),
                row_item_bg: Color::from_rgb8(38, 40, 52),
                row_hover_bg: Color::from_rgb8(58, 62, 80),
                row_selected_bg: Color::from_rgb8(70, 50, 85),
                row_playing_bg: Color::from_rgb8(50, 75, 60),
                row_playing_border: Color::from_rgb8(80, 250, 123),
                badge_bg: Color::from_rgb8(48, 45, 65),
                badge_text: Color::from_rgb8(80, 250, 123),
                visualizer_low: Color::from_rgb8(80, 250, 123),
                visualizer_mid: Color::from_rgb8(189, 147, 249),
                visualizer_high: Color::from_rgb8(255, 121, 198),
            },
            Self::SolarizedLight => ThemePalette {
                name: "Solarized Light",
                description: "Clean daylight high-contrast palette with sapphire blue accents",
                is_dark: false,
                bg_root: Color::from_rgb8(241, 245, 249),
                bg_panel: Color::from_rgb8(255, 255, 255),
                bg_card: Color::from_rgb8(248, 250, 252),
                bg_card_hover: Color::from_rgb8(235, 240, 248),
                border: Color::from_rgb8(203, 213, 225),
                border_subtle: Color::from_rgb8(226, 232, 240),
                accent: Color::from_rgb8(37, 99, 235),
                accent_hover: Color::from_rgb8(29, 78, 216),
                accent_text: Color::WHITE,
                text_primary: Color::from_rgb8(15, 23, 42),
                text_secondary: Color::from_rgb8(71, 85, 105),
                text_muted: Color::from_rgb8(148, 163, 184),
                nav_selected_bg: Color::from_rgb8(219, 234, 254),
                nav_selected_border: Color::from_rgb8(37, 99, 235),
                row_item_bg: Color::from_rgb8(255, 255, 255),
                row_hover_bg: Color::from_rgb8(241, 245, 249),
                row_selected_bg: Color::from_rgb8(224, 238, 255),
                row_playing_bg: Color::from_rgb8(220, 252, 231),
                row_playing_border: Color::from_rgb8(34, 197, 94),
                badge_bg: Color::from_rgb8(226, 232, 240),
                badge_text: Color::from_rgb8(15, 118, 110),
                visualizer_low: Color::from_rgb8(37, 99, 235),
                visualizer_mid: Color::from_rgb8(13, 148, 136),
                visualizer_high: Color::from_rgb8(234, 88, 12),
            },
        }
    }
}

impl Default for ThemePalette {
    fn default() -> Self {
        PlayerTheme::default().palette()
    }
}

