[workspace]
members = [
    "crates/audio-engine",
    "crates/plugin-api",
    "apps/kanono-player",
    "plugins/example-component",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
cpal = "0.15"
crossbeam-channel = "0.5"
iced = { version = "0.12", features = ["tokio"] }
libloading = "0.8"
symphonia = { version = "0.5.4", features = ["mp3", "flac", "wav", "pcm"] }