[package]
name = "kanono-audio-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cpal.workspace = true
crossbeam-channel.workspace = true
crossbeam-queue.workspace = true
ebur128.workspace = true
id3.workspace = true
libopus_sys.workspace = true
rusqlite.workspace = true
symphonia.workspace = true
walkdir.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "audio_callback"
harness = false
